
#the purpose of this script is to add extra info to the result not directly generated by the pipeline. This includes adjusting the way normalisation is conducted depending on the method. 
#we also adjust the correlation and RMSE info to use method specific normalised values.
library(stringr)
library(Hmisc)
library(dplyr)

#load the normalisation functions
source('./method_specific_normalisation.R')

files <- list.files('/shared-workspace/jfisher2/analyses/protein_prediction_publication/benchmarking', pattern = 'Rdata',full.names = F)

#function for normalizing specific to sctranslator

prefixes <- str_remove(files,'benchmark_predictions\\.Rdata')

numeric_prefixes <- c("0.0625_1_", "0.125_1_",  "0.25_1_" ,"0.5_1_","1_1_"  )


for(prefix in prefixes){
 
  file <- files[grep(paste0('^',prefix), files)]
  load(paste0('/shared-workspace/jfisher2/analyses/protein_prediction_publication/benchmarking/',file))

  
  if(prefix %nin% numeric_prefixes){
    print(prefix)
    predList$scTranslator_fewshot <- NULL
    predList$scTranslator_pretrain <- NULL
    corrList$scTranslator_fewshot <- NULL
    corrList$scTranslator_pretrain <- NULL
    scorrList$scTranslator_fewshot <- NULL
    scorrList$scTranslator_pretrain <- NULL
    RMSEList$scTranslator_fewshot <- NULL
    RMSEList$scTranslator_pretrain <- NULL
    NRMSEList$scTranslator_fewshot <- NULL
    NRMSEList$scTranslator_pretrain <- NULL
    truthList$scTranslator_fewshot <- NULL
    truthList$scTranslator_pretrain <- NULL
  }
  save(predList, corrList, scorrList, RMSEList, NRMSEList, truthList, file = paste0('/shared-workspace/jfisher2/analyses/protein_prediction_publication/benchmarking/',file) )
  
}
  
for(prefix in prefixes){
  print(prefix)
  #get raw prot counts
  testing_data_prot_raw <- read.csv( paste0('/shared-workspace/jfisher2/analyses/protein_prediction_publication/benchmarking/testing_files/',prefix, 'testing_data_prot_raw.csv') , row.names=1)
  #get seurat normalised CLR prot counts
  testing_data_prot_norm <- read.csv( paste0('/shared-workspace/jfisher2/analyses/protein_prediction_publication/benchmarking/testing_files/',prefix, 'testing_data_prot_norm.csv') , row.names=1)
  #get metadata for donor variable 
  meta <- read.csv(paste0('/shared-workspace/jfisher2/analyses/protein_prediction_publication/benchmarking/training_files/',prefix, 'metadata.csv'), row.names = 1)
  meta <- meta[colnames(testing_data_prot_raw),]
  
  testing_data_prot_SPECK <- testing_data_prot_norm
  testing_data_prot_Seurat <- testing_data_prot_norm
  testing_data_prot_scLinear <- testing_data_prot_norm
  testing_data_prot_BABEL <- testing_data_prot_norm
  testing_data_prot_scMMT <- testing_data_prot_norm
  
  testing_data_prot_scTranslator_fewshot <- apply(testing_data_prot_raw,2,FUN=normalise_scTranslator)  
  testing_data_prot_scTranslator_pretrain <- testing_data_prot_scTranslator_fewshot 
  
  testing_data_prot_cTP_net <- normalise_cTPnet(testing_data_prot_raw) 

  testing_data_prot_sciPENN <- normalise_scanpy(testing_data_prot_raw, zscore = T, batch_vector = meta$donor )

  testing_data_prot_totalVI <- normalise_scanpy(testing_data_prot_raw,  cellnorm = F, lognorm = T)
  
  
  file <- files[grep(paste0('^',prefix), files)]
  load(paste0('/shared-workspace/jfisher2/analyses/protein_prediction_publication/benchmarking/',file))
  
  
  #remove scTranslator
  if(prefix %nin% numeric_prefixes){
    predList$scTranslator_fewshot <- NULL
    predList$scTranslator_pretrain <- NULL
  }
  
  #iterate over methods and compute
  NRMSEList <- list()
  scorrList <- list()
  truthList <- list()
  for(n in names(predList)){
    print(n)
    pred <- predList[[n]]

    truth_name <- paste0('testing_data_prot_',n)
    truth <- get(truth_name)
    colnames(truth) <- sub("^X", "", colnames(truth))
    
    if(grepl('scTranslator', n)){
      if(dim(pred)[1] > dim(pred)[2]){
        pred <- t(pred)
      }
      if(any(rownames(pred) %nin% rownames(truth))){
        rownames(truth) <- str_replace_all(rownames(truth),'\\/','-')
      }

    }
    predList[[n]] <- pred
    
    scorVal <- cor(t(pred), t(truth[rownames(pred),] ), method = 'spearman')
    corVal <- cor(t(pred), t(truth[rownames(pred),] ), method = 'pearson')
    
    corVal <- diag(corVal)
    names(corVal) <- rownames(pred)
    corrList[[n]] <- corVal
    
    scorVal <- diag(scorVal)
    names(scorVal) <- rownames(pred)
    scorrList[[n]] <- scorVal
  
    diff <- pred - truth[rownames(pred),]
    avgs <- apply(truth,1,FUN=mean)
    sds <- apply(truth,1,FUN=sd)
    RMSEval <- apply(diff, 1, FUN=function(x){sqrt(mean(x)^2)})
    RMSEList[[n]] <- RMSEval

    #do normalisated RMSE
    NRMSEval <- RMSEval / sds[names(RMSEval)]
    NRMSEList[[n]] <- NRMSEval
    
    truthList[[n]] <- truth
  }
  
  save(predList, corrList, scorrList, RMSEList, NRMSEList, truthList, file = paste0('/shared-workspace/jfisher2/analyses/protein_prediction_publication/benchmarking/',file) )
}


#do the same thing for the dataset comparisons
savedir <- '~/workspace/analyses/protein_prediction_publication/'
datacomp_list <- load(paste0(savedir, '/dataset_comparison_repeat/compiled_outcomes.Rdata')) %>% get()

datasets <- c('Hao_etal','Leader_etal','Stephenson_etal_Healthy','Stephenson_etal_Covid','Zhang_etal')

shared_abs_full <- read.csv(paste0(savedir,'/repo/source_data/dataset_comparison_shared_antibodies.csv'))
shared_abs <- shared_abs_full[which(shared_abs_full$shared),]

datacomp_list <- list()
#"Stephenson_etal_Healthy_vs_Stephenson_etal_Healthy"
for(i in datasets){
  for(j in datasets){
    
    print(paste0(i,'_vs_',j))
    testing_data_prot_raw <- read.csv( paste0('/shared-workspace/jfisher2/analyses/protein_prediction_publication/dataset_comparison_repeat/',i,'_vs_',j, '/output/input_files/testing_data_prot_raw.csv') , row.names=1)
    #get seurat normalised CLR prot counts
    testing_data_prot_norm <- read.csv( paste0('/shared-workspace/jfisher2/analyses/protein_prediction_publication/dataset_comparison_repeat/',i,'_vs_',j, '/output/input_files/testing_data_prot_norm.csv') , row.names=1)
    #get metadata for donor variable 
    meta <- read.csv( paste0('/shared-workspace/jfisher2/analyses/protein_prediction_publication/dataset_comparison_repeat/',i,'_vs_',j, '/output/input_files/metadata_test.csv') , row.names=1)
    
    colnames(testing_data_prot_raw) <- sub("^X", "", colnames(testing_data_prot_raw))
    colnames(testing_data_prot_norm) <- sub("^X", "", colnames(testing_data_prot_norm))
    colnames(testing_data_prot_raw) <- sub("\\.", "-", colnames(testing_data_prot_raw))
    colnames(testing_data_prot_norm) <- sub("\\.", "-", colnames(testing_data_prot_norm))
    
    dset_prefixj <- paste0(str_split(j,'_')[[1]][1:2], collapse='_')
    dset_prefixi <- paste0(str_split(i,'_')[[1]][1:2], collapse='_')
    
    
    testing_data_prot_scTranslator_fewshot <- apply(testing_data_prot_raw,2,FUN=normalise_scTranslator)  

    testing_data_prot_cTP_net <- normalise_cTPnet(testing_data_prot_raw) 
    
    testing_data_prot_sciPENN <- normalise_scanpy(testing_data_prot_raw, zscore = T, batch_vector = meta$donor )

    testing_data_prot_totalVI <- normalise_scanpy(testing_data_prot_raw,  cellnorm = F, lognorm = T)
    
    #iterate over methods and compute
    datacomp_list[[paste0(i,'_vs_',j)]]$correlation <- list()
    datacomp_list[[paste0(i,'_vs_',j)]]$scorrelation <- list()
    datacomp_list[[paste0(i,'_vs_',j)]]$RMSE <- list()
    datacomp_list[[paste0(i,'_vs_',j)]]$NRMSE <- list()
    datacomp_list[[paste0(i,'_vs_',j)]]$truth <- list()
    
    #match the rownames to Hao
    testing_data_prot_norm <- testing_data_prot_norm[shared_abs[,dset_prefixj],]
    ind <- match(rownames(testing_data_prot_norm) , shared_abs[,dset_prefixj])
    rownames(testing_data_prot_norm) <- shared_abs[na.omit(ind), 'Hao_etal']
    
    testing_data_prot_raw <- testing_data_prot_raw[shared_abs[,dset_prefixj],]
    ind <- match(rownames(testing_data_prot_raw) , shared_abs[,dset_prefixj])
    rownames(testing_data_prot_raw) <- shared_abs[na.omit(ind), 'Hao_etal']
    
    testing_data_prot_scTranslator_fewshot <- testing_data_prot_scTranslator_fewshot[shared_abs[,dset_prefixj],]
    ind <- match(rownames(testing_data_prot_scTranslator_fewshot) , shared_abs[,dset_prefixj])
    rownames(testing_data_prot_scTranslator_fewshot) <- shared_abs[na.omit(ind), 'Hao_etal']
    testing_data_prot_scTranslator_pretrain <- testing_data_prot_scTranslator_fewshot 
    
    testing_data_prot_cTP_net <- testing_data_prot_cTP_net[shared_abs[,dset_prefixj],]
    ind <- match(rownames(testing_data_prot_cTP_net) , shared_abs[,dset_prefixj])
    rownames(testing_data_prot_cTP_net) <- shared_abs[na.omit(ind), 'Hao_etal']
    
    
    testing_data_prot_sciPENN <- testing_data_prot_sciPENN[shared_abs[,dset_prefixj],]
    ind <- match(rownames(testing_data_prot_sciPENN) , shared_abs[,dset_prefixj])
    rownames(testing_data_prot_sciPENN) <- shared_abs[na.omit(ind), 'Hao_etal']
    
    testing_data_prot_totalVI <- testing_data_prot_totalVI[shared_abs[,dset_prefixj],]
    ind <- match(rownames(testing_data_prot_totalVI) , shared_abs[,dset_prefixj])
    rownames(testing_data_prot_totalVI) <- shared_abs[na.omit(ind), 'Hao_etal']
    
    testing_data_prot_SPECK <- testing_data_prot_norm
    testing_data_prot_Seurat <- testing_data_prot_norm
    testing_data_prot_scLinear <- testing_data_prot_norm
    testing_data_prot_BABEL <- testing_data_prot_norm
    testing_data_prot_scMMT <- testing_data_prot_norm
    
    meta <- meta[colnames(testing_data_prot_raw),]

    x <- load( paste0('/shared-workspace/jfisher2/analyses/protein_prediction_publication/dataset_comparison_repeat/',i,'_vs_',j, '/output/predictions.Rdata'))
    predList <- get(x[1])
    #predList <- datacomp_list[[paste0(i,'_vs_',j)]]$predictions
    
    if("scTranslator_notrain"  %in% names(predList)){
      predList[["scTranslator_pretrain" ]] <- predList[["scTranslator_notrain" ]] 
      predList[["scTranslator_notrain" ]] <- NULL

    }
    for(n in names(predList)){
      
      print(n)
      pred <- predList[[n]]
      #pred <- datacomp_list[[paste0(i,'_vs_',j)]]$predictions[[n]]
      
      if(dim(pred)[1] > dim(pred)[2]){
        pred <- t(pred)
      }
      
      if(!all(rownames(pred) %in% shared_abs_full$Hao_etal)){
        dset <- dset_prefixi
        feat <- rownames(pred)[rownames(pred) %in% shared_abs[,dset]]
        if(length(feat) == 0){
          dset <- dset_prefixj
          feat <- rownames(pred)[rownames(pred) %in% shared_abs[,dset]]
        }
        pred <- pred[feat,]
        ind <- match(rownames(pred) , shared_abs[,dset])
        rownames(pred) <- shared_abs[na.omit(ind), 'Hao_etal']
      }else{
        pred <- pred[which(rownames(pred)%in%shared_abs$Hao_etal),]
      }
    
      
      truth_name <- paste0('testing_data_prot_',n)
      truth <- get(truth_name)
      #set NAs to zero
      truth[is.na(truth)] <- 0
      
      if(grepl('scTranslator', n)){

        if(any(rownames(pred) %nin% rownames(truth))){
          rownames(truth) <- str_replace_all(rownames(truth),'\\/','-')
        }
        
      }

      scorVal <- cor(t(pred), t(truth[rownames(pred),] ), method = 'spearman')
      corVal <- cor(t(pred), t(truth[rownames(pred),] ), method = 'pearson')
      
      corVal <- diag(corVal)
      names(corVal) <- rownames(pred)

      scorVal <- diag(scorVal)
      names(scorVal) <- rownames(pred)
      
      diff <- pred - truth[rownames(pred),]
      avgs <- apply(truth,1,FUN=mean)
      sds <- apply(truth,1,FUN=sd)
      RMSEval <- apply(diff, 1, FUN=function(x){sqrt(mean(x)^2)})

      
      #do normalisated RMSE
      NRMSEval <- RMSEval / sds[names(RMSEval)]

      
      datacomp_list[[paste0(i,'_vs_',j)]]$predictions[[n]] <- pred
      datacomp_list[[paste0(i,'_vs_',j)]]$correlation[[n]] <- corVal
      datacomp_list[[paste0(i,'_vs_',j)]]$scorrelation[[n]] <- scorVal
      datacomp_list[[paste0(i,'_vs_',j)]]$RMSE[[n]] <- RMSEval
      datacomp_list[[paste0(i,'_vs_',j)]]$NRMSE[[n]] <- NRMSEval
      datacomp_list[[paste0(i,'_vs_',j)]]$truth[[n]] <- truth

    }
    
  }
}


save(datacomp_list , file = paste0(savedir, '/dataset_comparison_repeat/compiled_outcomes.Rdata'))

